### ISSUE TITLE
Cannot modify spaces after trailing comma

### ISSUE THREAD

**Issue by kayhayen** [Psycojoker/redbaron#39]
The following code:

(self, )

Note the trailing space after the comma. I was writing a modifier that removes trailing and leading spaces. And came up with this:

    if "\n" not in tuple_node.dumps():
        tuple_node.second_formatting = ""
        tuple_node.third_formatting = ""

        for argument in tuple_node.value:
            if argument.type in ("string", "binary_string"):
                argument.second_formatting = ""

Note, that I find it strange, that I need to drop leading spaces from contained strings (same for
call nodes, strings seem to attract whitespace for no good reason, where I would naturally attribute it to the outside). I tried setting all four formattings to "x#", and this resulted a string containing them, plus still a space after the comma. Where is it hiding? The name typed argument doesn't indicate anything in its dict.

**Comment by Psycojoker** [comment]
String aren't greedy anymore so this shouldn't be a problem now, don't hesitate to complain if it's still the case.

**Comment by kayhayen** [comment]
Great, just ran it with 0.3 over my code, and it found a few extra places to correct.
