### ISSUE TITLE
Questionable behavior for NodeList.index_on_parent

### ISSUE THREAD

**Issue by ibizaman** [Psycojoker/redbaron#46]
Due to the (this line)[https://github.com/Psycojoker/redbaron/blob/master/redbaron.py#L935], the following code can insert lines at wrong places:

    item.parent.insert(item.index_on_parent, foo)

This is because the index_on_parent was used by the "path" feature. The path specific behavior should be refactored inside the Path class.

A temporary fix is to use:

    item.parent.insert(item.parent.index(item), foo)

**Comment by Psycojoker** [comment]
Yes, that sucks, I'm going to make <code>item.index_on_parent</code> behave like <code>item.parent.insert(item.parent.index(item), foo)</code> and add something like <code>item.index_on_parent_raw</code>.

**Comment by ibizaman** [comment]
This looks really related to https://github.com/Psycojoker/redbaron/pull/52 fix this ?
I'll make some tests for this.

**Comment by Psycojoker** [comment]
Fxied in https://github.com/Psycojoker/redbaron/commit/5f246063d001c5d9550b0ba079e098e6426fd109

And I've forgot to do this github message commit stuff again.
