### ISSUE TITLE
Can't use redbaron in IPython notebook

### ISSUE THREAD

**Issue by remram44** [Psycojoker/redbaron#50]
redbaron calls `fileno()` on `sys.stdout` which raises unhandled `UnsupportedOperation`.

```
---------------------------------------------------------------------------
UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-10-7a726da5bd0a> in <module>()
----> 1 str(tree)

C:\Python2.7\lib\site-packages\redbaron.pyc in __str__(self)
   1270         to_return = ""
   1271         for number, value in enumerate(self.data):
-> 1272             to_return += ("%-3s " % number) + "\n    ".join(value.__repr__().split("\n"))
   1273             to_return += "\n"
   1274         return to_return

C:\Python2.7\lib\site-packages\redbaron.pyc in __repr__(self)
    852     def __repr__(self):
    853         # the isinstance here is for building sphinx doc
--> 854         if isinstance(sys.stdout, StringIO) or os.isatty(sys.stdout.fileno()):
    855             return self.__str__()
    856 

C:\Python2.7\lib\site-packages\IPython\kernel\zmq\iostream.pyc in fileno(self)
    192 
    193     def fileno(self):
--> 194         raise UnsupportedOperation("IOStream has no fileno.")
    195 
    196     def write(self, string):

UnsupportedOperation: IOStream has no fileno.
```

http://nbviewer.ipython.org/gist/remram44/449041cd67ad390037b8

**Comment by Psycojoker** [comment]
Hello,

There is great chances that this is actually already fixed but unreleased (see: https://github.com/Psycojoker/redbaron/issues/44). Can you try using RedBaron master to see if this works please?

I'll do a bugfix release if it's the case.

Thanks for reporting :)

**Comment by remram44** [comment]
I can reproduce the bug on master; zmq's `sys.stdout` does have `fileno()`, it just raises when called.

**Comment by remram44** [comment]
This should be a simple matter of catching `UnsupportedOperation`, however I do not understand why the `isatty()` check is here to begin with. `__repr__()` works differently depending on what `sys.stdout` is, regardless of whether `__repr__()` is going there or not?

**Comment by Psycojoker** [comment]
Yes, in a ipython shell, __repr__ displays the selected code (highlighted with pygment) like BeautifulSoup displays you the selected html. But when running a script you might not know where you are and what you have selected at this point so we display a more common repr (much like any python object).

I'm going to look at it in some minutes.

**Comment by remram44** [comment]
The problem with that approach is that you have no accurate way of knowing if the result of `__repr__` is eventually meant to be printed in the terminal or not. In IPython, the kernel is not attached to a terminal, and yet the result is sent through a ZMQ socket and printed. In contrast, a non-interactive function might still happen in a process which is still connected to a terminal.

The current approach already does weird stuff, for example:
```
>>> tree.help
<bound method NodeList.help of 0   self.get_input('some_port')
1   u'\n'
2   a = self.force_get_input('something', 2)
3   u'\n'
4   if False:
        self.set_output('port_name', False)

>
```

AFAIK beautifulsoup doesn't try anything funny here either ([link](http://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/head:/bs4/element.py?start_revid=353#L974)).

I'm not sure what to recommend though because `__str__()`'s output is indeed useful :cry:

**Comment by Psycojoker** [comment]
Yes, BeautifulSoup always print the html code which is fine. In our case we sometime ends up printing formatting information like white spaces which turns out to be extremely confusing for the user.

So, after one quick google search "how to detect that you are in a python shell" we ends up with this situation that doesn't seems very optimal :/

Right now I don't know have an opinion on the best approach to have. I'll start by fixing it for ipython and catching other exceptions to fall back on a default behavior.

**Comment by Psycojoker** [comment]
After playing with "def _repr_html_" of the notebook this end up looking like this:
![2015-01-13-235917_754x677_scrot](https://cloud.githubusercontent.com/assets/41827/5731132/65ff4c92-9b80-11e4-977c-0faebbf63415.png)

Should be way more usable. It's pushed on master.

Tell me if you find any more bugs ;)

**Comment by Psycojoker** [comment]
Closing this issue for now, don't hesitate to complain/reopen it/open other issues if needed.

**Comment by remram44** [comment]
This is great, thanks :smiley:
