### ISSUE TITLE
Replacing ImportNode with FromImport Results in Error

### ISSUE THREAD

**Issue by keyanp** [Psycojoker/redbaron#57]
I've been using RedBaron to modify some import statements, I was successful in being able to change FromImportNodes into ImportNodes, but not the other way around. When trying to make this change:

`import flask.ext.foo` --> `from flask_foo import foo`

I got an error which is in the below gist, as is the code that caused the problem. I was able to get something working for my purposes, but the prompt asked for an issue submission so here it is!

https://gist.github.com/keyanp/a9f86e3bd8f7feb68fbc

**Comment by Psycojoker** [comment]
Hello @keyanp,

The general behavior of <code>.replace</code> is that it's expecting a **full** valid python program (this is quite a limitation but not for here), so, from your gist, you should probably change:

```python
imports[x].replace("from flask_%s import" % (package, package))
```

To:


```python
imports[x].replace("from flask_%s import %s" % (package, package))
```

(I've added a second "%s" in the string to make it a valid python program).

Hope it helps,
