### ISSUE TITLE
Cannot modify whitespace from function declarations

### ISSUE THREAD

**Issue by kayhayen** [Psycojoker/redbaron#59]
Hello,

having a function:

def f( a, b ):
   pass

I would like to set third_formatting and fourth_formatting on it, but it says "unhandled case", when I set this to "". My intent is to write code, which automatically formats function definition arguments to
contain new-lines as necessary only, and no leading or trailing space for arguments.

Can you please add support for these.

**Comment by Psycojoker** [comment]
Hello,

I've just pushed a patch to fix this (and this will basically be fixed for every "code block node" https://redbaron.readthedocs.org/en/latest/nodes_reference.html#codeblocknode). Sorry for the big delay, life isn't very compelling with me for redbaron right now :/

Waiting for your feedback,

**Comment by kayhayen** [comment]
Hello there,

I just pip installed things, and can confirm, that the function white space is now properly writable, for what I use:

    # This is between "def" and function name.
    def_node.first_formatting = " "

    # This is after the opening/closing brace, we don't want it there.
    def_node.third_formatting = ""
    def_node.fourth_formatting = ""

    # This is to insert/remove spaces or new lines, depending on line length
    # so far, but is not functional at all.
    for argument_node in def_node.arguments:
        argument_node.first_formatting = ""
        argument_node.second_formatting = " "

However, the last part doesn't work at all, nothing changes, whatever I assign there. I would like
to be able to modify a function like this:

    def f(a, b):
        pass

to become

   def f(a,
           b):
        pass

with the choice of " " or "\n" depending on accumulated line length so far.

Yours,
Kay

**Comment by kayhayen** [comment]
Meanwhile I have observed and effect of

argument_node.first_formatting

for keyword argument, it allows to assign spaces before the "=". I guess, I might have to check the argument type, or look for more formatting values.

**Comment by ibizaman** [comment]
I guess that's a style decision and not a RedBaron bug, right ?

**Comment by Psycojoker** [comment]
Hello,

The "\n" needs to be put on the <code>CommaNode</code> here, as you have guessed, the formatting for the ArgumentNode are formatting regarding the stuff arround the "=" when its present.

I'm closing this ticket, one is already open in baron repo regarding generating detailed doc on the rendering of nodes, that would hopefully have made you this information way more accessible for you.

Kind regards,
