### ISSUE TITLE
Inconsistance in numerical node behavior

### ISSUE THREAD

**Issue by remram44** [Psycojoker/redbaron#65]
As far as I know, number literals can be one of `IntNode`, `FloatNode`, `OctaNode`, `HexaNode`, `LongNode`. However they don't appear in the code or doc, except for `IntNode`, which works differently because its value is a number instead of str.

So I'm left with:
```python
def get_int_value(node):
    NUMBERS = IntNode, FloatNode, OctaNode, HexaNode, LongNode

    if isinstance(node, NUMBERS):
        if isinstance(node, IntNode):
            return node.value
        else:
            return ast.literal_eval(node.value)
    else:
        raise ValueError

code = RedBaron('a = 12\na = 0xC')
get_int_value(code[0].assign.value), get_int_value(code[1].assign.value)
```

**Comment by Psycojoker** [comment]
Hello,

Yes, this is bad, I think that I'm going to switch back to string everywhere and providing a <code>.to_python()</code> method that does a <code>ast.literal</code>.

Thanks for reporting,

**Comment by remram44** [comment]
Awesome! That'd be great, thanks!

**Comment by Psycojoker** [comment]
https://redbaron.readthedocs.org/en/latest/other.html#to-python

**Comment by remram44** [comment]
I'll be using that!
